#!/bin/bash
number=10000
formatted_number=$(printf "%05d" "$number")
echo "file_"$formatted_number
echo `expr $number + 1`
n_processes=2

current_size=$(echo "scale=0; sqrt($n_processes * $number^2)" | bc)
echo $current_size

for n_processes in {1..8..1}
do
    current_size=$(echo "scale=0; sqrt($n_processes * $number^2)" | bc)
    echo $current_size
done