#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <mpi.h>

#define NELEM    2

void read_pgm_image( unsigned char **image, int *maxval, int *xsize, int *ysize, const char *image_name);

int main(int argc, char **argv)
{
  int i, rank, size;
  unsigned char buf[NELEM];
  char fname[] = "arr1D.pgm";
  MPI_File   fh;
  MPI_Offset disp;

/* --------------------------------------------------------
   0. Initialize the MPI execution environment
   -------------------------------------------------------- */

  MPI_Init (&argc, &argv);
  MPI_Comm_rank (MPI_COMM_WORLD, &rank);
  MPI_Comm_size (MPI_COMM_WORLD, &size);

/* --------------------------------------------------------
   1. Initialize array
   -------------------------------------------------------- */

  for (i = 0; i < NELEM; i++){
    if(rank==0)
      buf[i] = 255;
    else buf[i] = 0;
  }

/* --------------------------------------------------------
   2. Delete, re-open file and write
   -------------------------------------------------------- */

  MPI_File_delete(fname, MPI_INFO_NULL);
  MPI_File_open(  MPI_COMM_WORLD, fname, 
                  MPI_MODE_CREATE | MPI_MODE_RDWR, 
                  MPI_INFO_NULL, &fh  );
  MPI_File_close(&fh);

  // Initialize PGM file Header
  // fprintf(image_file, "P5\n# generated by\n# Elena Rivaroli and Samuele D'Avenia\n%d %d\n%d\n", xsize, ysize, maxval);
  if (rank == 0) {
    printf("Process %d is doing it\n", rank);
    FILE* file_stream = fopen(fname, "w");  // Open a FILE* stream
    int xsize, ysize, maxval;
    xsize = 2;
    ysize = 2;
    maxval = 255;
    if (file_stream != NULL) {
      int max_value = size - 1;
      fprintf(file_stream, "P5\n# generated by\n# Elena Rivaroli and Samuele D'Avenia\n%d %d\n%d\n", xsize, ysize, maxval);
      fclose(file_stream);
    } else {
      fprintf(stderr, "Failed to open the PGM file for writing.\n");
      MPI_Abort(MPI_COMM_WORLD, 1);
    }
  }
  MPI_Barrier(MPI_COMM_WORLD);



// Contiguous data, file view
  /*disp = rank*NELEM*sizeof(double);
  MPI_File_set_view(fh, disp, MPI_DOUBLE, MPI_DOUBLE, "native", MPI_INFO_NULL);
  MPI_File_write(fh, buf, NELEM, MPI_DOUBLE, MPI_STATUS_IGNORE);  */

  MPI_File_open(  MPI_COMM_WORLD, fname, 
                  MPI_MODE_APPEND | MPI_MODE_RDWR, 
                  MPI_INFO_NULL, &fh  );
  disp = rank*NELEM*sizeof(unsigned char);
  MPI_File_seek(fh, disp, MPI_SEEK_CUR);
  MPI_File_write_all(fh, buf, NELEM, MPI_UNSIGNED_CHAR, MPI_STATUS_IGNORE);

  MPI_File_close(&fh);
  MPI_Finalize();
  return 0;
}
